import turtle
import time
import random

#Run intro screen
def intro_screen():
	turtle.setup(800,800)
	turtle.screensize(800,800)
	window = turtle.Screen()
	window.bgcolor("black")
	time.sleep(3)
	window.title("THE CRAZY GAME")
	turtle.color("Yellow")
	turtle.write("WELCOME TO URAVITY",True,align="center",font =("Arial",50,"normal"))
	time.sleep(1)
	turtle.clear()
	turtle.write("A GAME LIKE NEVER ",True,align="right",font =("Arial",50,"normal"))
	time.sleep(1)
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.write("BEFORE ",True,align="center",font =("Arial",10,"normal"))
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.color("pink")
	turtle.write("BEFORE ",True,align="center",font =("Arial",20,"normal"))
	turtle.clear()
	turtle.color("blue")
	turtle.write("BEFORE ",True,align="center",font =("Arial",30,"normal"))
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.clear()
	turtle.color("orange")
	turtle.write("BEFORE ",True,align="center",font =("Arial",40,"normal"))
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.clear()
	turtle.color("red")
	turtle.write("BEFORE ",True,align="center",font =("Arial",50,"normal"))
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.clear()
	turtle.color("green")
	turtle.write("BEFORE ",True,align="center",font =("Arial",60,"normal"))
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.clear()
	turtle.color("orange")
	turtle.write("BEFORE ",True,align="center",font =("Arial",70,"normal"))
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.clear()
	turtle.color("red")
	turtle.write("BEFORE ",True,align="center",font =("Arial",80,"normal"))
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.clear()
	turtle.color("blue")
	turtle.write("BEFORE ",True,align="center",font =("Arial",90,"normal"))
	turtle.reset()
	turtle.goto(0,0)
	time.sleep(0.3)
	turtle.clear()
	turtle.color("cyan")
	turtle.write("BEFORE ",True,align="center",font =("Arial",100,"normal"))		